name: Makefile CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.17
      
    - name: Test User service
      run: make test
      working-directory: user_api
    - name: Test crypto service
      run: make test
      working-directory: crypto_service_api
